<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="UpdateProducts.aspx.cs" Inherits="Prog4.UpdateProducts" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
   
    <form id="form2" runat="server">
        <asp:DetailsView ID="DetailsView1" 
            runat="server" 
            AllowPaging="True" 
            BackColor="White" 
            BorderColor="#CCCCCC" 
            BorderStyle="None" 
            BorderWidth="1px" 
            CellPadding="4" 
            DataKeyNames="ProductID" 
            DataSourceID="SqlDataSource1" 
            ForeColor="Black" 
            GridLines="Horizontal" 
            Height="47px" 
            Width="385px" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            AutoGenerateInsertButton="True" 
            OnPageIndexChanging="DetailsView1_PageIndexChanging" AutoGenerateRows="False">
            <EditRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <Fields>
                <asp:BoundField DataField="ProductID" HeaderText="ProductID" ReadOnly="True" SortExpression="ProductID" />
                <asp:BoundField DataField="ProductName" HeaderText="ProductName" SortExpression="ProductName" />
                <asp:BoundField DataField="UnitPrice" HeaderText="UnitPrice" SortExpression="UnitPrice" />
                <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
            </Fields>
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
            <PagerSettings runat ="server" FirstPageText="First" LastPageText="Last" Mode="NextPreviousFirstLast" NextPageText="Next" PreviousPageText="Previous" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
        </asp:DetailsView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:UWPCS3870ConnectionString2 %>" SelectCommand="SELECT * FROM [Product]" DeleteCommand="DELETE FROM Product
WHERE ProductID = @ProductID" InsertCommand="INSERT INTO Product(ProductID, ProductName, UnitPrice, Description) VALUES (@ProductID, @ProductName, @UnitPrice, @Description)" UpdateCommand="UPDATE Product SET ProductID =@ProdcutID, ProductName =@ProductName, UnitPrice =@UnitPrice, Description =@Description"></asp:SqlDataSource>
    </form>
   
</asp:Content>
